import { ListView } from "std-widgets.slint";
export struct SongDatafListView {
  name: string,
  album: string,
  performer: string,
  genre: string,
}

export component ListSongView inherits Rectangle {
    property <[SongDatafListView]> SongList: [
        {
            name: "3 trokas",
            album: "Pa' las babys y belikeada",
            performer: "Fuerza Regida",
            genre: "Corridos Tumbados"
        },
        {
            name: "LADY GAGA",
            album: "GÉNESIS",
            performer: "Peso Pluma, Gabito Ballesteros, Junior H",
            genre: "Corridos Tumbados"
        },
        {
            name: "Bohemian Rhapsody",
            album: "A Night at the Opera",
            performer: "Queen",
            genre: "Rock"
        },
        {
            name: "El Azul",
            album: "Sencillo",
            performer: "Junior H, Peso Pluma",
            genre: "Regional Mexicano"
        },
        {
            name: "Blinding Lights",
            album: "After Hours",
            performer: "The Weeknd",
            genre: "Synth-pop"
        },
        {
            name: "La Chona",
            album: "Con un Mismo Corazón",
            performer: "Los Tucanes de Tijuana",
            genre: "Norteño"
        },
        {
            name: "Master of Puppets",
            album: "Master of Puppets",
            performer: "Metallica",
            genre: "Thrash Metal"
        }
    ];
    width: 100%;
    height: 100%;
    background: #34312D;
    VerticalLayout {
        padding-top: root.height * 0.02;
        padding-bottom: root.height * 0.02;
        Rectangle {
            width: 100%;
            height: 3%;

            HorizontalLayout {
                spacing: root.width * 0.008;
                padding-left: root.width * 0.01;
                Text {
                    width: 25%;
                    horizontal-alignment: left;
                    vertical-alignment: center;
                    color: white;
                    text: "Title";
                }

                Text {
                    width: 25%;
                    horizontal-alignment: left;
                    vertical-alignment: center;
                    color: white;
                    text: "Performer";
                }

                Text {
                    width: 25%;
                    vertical-alignment: center;
                    horizontal-alignment: left;
                    color: white;
                    text: "Album";
                }

                Text {
                    width: 25%;
                    vertical-alignment: center;
                    horizontal-alignment: left;
                    color: white;
                    text: "Genre";
                }
            }
        }

        Rectangle {
            width: root.width;
            height: 1px;
            background: #ddd;
        }

        ListView {
            for song in SongList: VerticalLayout {
                Rectangle {
                    interaction := TouchArea { }

                    background: interaction.has-hover ? #C9A96E : #0000;
                    width: 100%;
                    height: root.height * 0.05;
                    HorizontalLayout {
                        spacing: root.width * 0.008;
                        padding-left: root.width * 0.01;
                        padding-right: root.width * 0.01;
                        Text {
                            overflow: elide;
                            width: 25%;
                            horizontal-alignment: left;
                            vertical-alignment: center;
                            color: #ddd;
                            text: song.name;
                        }

                        Text {
                            overflow: elide;
                            width: 25%;
                            horizontal-alignment: left;
                            vertical-alignment: center;
                            color: #ddd;
                            text: song.performer;
                        }

                        Text {
                            overflow: elide;
                            width: 25%;
                            vertical-alignment: center;
                            horizontal-alignment: left;
                            color: #ddd;
                            text: song.album;
                        }

                        Text {
                            overflow: elide;
                            width: 25%;
                            vertical-alignment: center;
                            horizontal-alignment: left;
                            color: #ddd;
                            text: song.genre;
                        }
                    }
                }

                Rectangle {
                    width: 100%;
                    height: 1px;
                    background: #C9A96E;
                }
            }
        }
    }
}
