import { SongVizualizer } from "components/song_visualizer.slint";
import { InteractionButtons } from "components/interaction_buttons.slint";
import { VolumeVisualizer } from "components/volume_visualizer.slint";
import { MusicPlayer } from "components/music_player.slint";
import { ListSongView } from "components/list_song_view.slint";

export component AppWindow inherits Window {
    preferred-width: 1000px;
    preferred-height: 600px;

    min-width: 800px;
    min-height: 480px;
    callback open_folder_dialog <=> main_view.open_folder_dialog;
    callback start_mining <=> main_view.start_mining;
    callback search <=> main_view.search;
    callback update_person_data <=> main_view.update_person_data;
    callback add_group_member <=> main_view.add_group_member;
    in property mining_directory <=> main_view.mining_directory;
    in property song_list <=> main_view.SongList;
    // SongVizualizer {
    //     song_img: @image-url("/home/jesus-figueroa/Imágenes/plbyb.jpg");
    //     song_name: "Tres Trokas";
    //     song_performer: "Fuerza Regida";
    // }
main_view := ListSongView { }
}
