import { SongVizualizer } from "components/song_visualizer.slint";
import { InteractionButtons } from "components/interaction_buttons.slint";
import { VolumeVisualizer } from "components/volume_visualizer.slint";
import { MusicPlayer } from "components/music_player.slint";
import { ListSongView } from "components/list_song_view.slint";

export component AppWindow inherits Window {
    preferred-width: 1000px;
    preferred-height: 600px;

    min-width: 800px;
    min-height: 480px;

    // SongVizualizer {
    //     song_img: @image-url("/home/jesus-figueroa/Imágenes/plbyb.jpg");
    //     song_name: "Tres Trokas";
    //     song_performer: "Fuerza Regida";
    // }
ListSongView {

        search(texto) => {
        }
        update_person_data(id, nombre, nacimiento, muerte) => {
        }
        add_group_member(id, nombre, nacimiento, muerte) => {
        }
    }
}
